### ISSUE TITLE
Add "execute" function

### ISSUE THREAD

**Issue by tbwebb22** [decent-dao/fractal-module-treasury#19]
The treasury module needs an arbitrary "execute" function with the authorized modifier so that it can make arbitrary function calls, such as for claiming tokens.

**Comment by adamgall** [comment]
This should probably go on the Module Base contract, no?

**Comment by tbwebb22** [comment]
Ah yes, assuming we want this execute function on all modules, which I think makes sense. I'll close this and move it to the core repo.
